from fastapi import APIRouter, Depends, status, Query, Response
from fastapi.responses import StreamingResponse
import io
import csv
import json
from typing import Any, List
from backend.core.dependencies import get_current_active_user
from backend.models.user import User

router = APIRouter(prefix="/reports", tags=["Reports System"])

@router.get(
    "/generate",
    summary="Generate system reports (CSV, JSON, PDF)"
)
async def generate_report(
    report_type: str = Query(..., description="Report categories: training, prediction, digital_twin, scheduler, qhi, execution"),
    report_format: str = Query("json", description="Output format: csv, json, pdf"),
    current_user: User = Depends(get_current_active_user)
):
    """
    Dynamically generates performance and history reports in various serialization standards.
    """
    from backend.database.connection import MongoDBManager
    from backend.machine_learning.training.runner import AutonomousSimulationRunner
    from datetime import datetime
    qubit_count = AutonomousSimulationRunner.state.get("qubit_count", 5)
    db = MongoDBManager.get_database_by_qubits(qubit_count)
    
    from backend.config.constants import DBCollections
    collection_mapping = {
        "digital_twin": await DBCollections.get_active_collection_name(db, qubit_count, "digital_twins"),
        "training": await DBCollections.get_active_collection_name(db, qubit_count, "training"),
        "prediction": await DBCollections.get_active_collection_name(db, qubit_count, "predictions"),
        "scheduler": await DBCollections.get_active_collection_name(db, qubit_count, "scheduler"),
        "qhi": await DBCollections.get_active_collection_name(db, qubit_count, "qhi"),
        "execution": await DBCollections.get_active_collection_name(db, qubit_count, "execution")
    }
    
    if report_type.lower() == "comparison":
        report_data = [
            {"provider": "Mathematical Simulator", "t1_coherence_sec": 0.000100, "gate_error_rate": 0.0005, "readout_fidelity": 0.9900, "gate_speed_us": 0.02, "qubit_capacity": 5, "connectivity": "Full Mesh", "footprint": "Local RAM"},
            {"provider": "IBM Quantum (Torino)", "t1_coherence_sec": 0.000110, "gate_error_rate": 0.0004, "readout_fidelity": 0.9880, "gate_speed_us": 0.05, "qubit_capacity": 133, "connectivity": "Heavy-Hex", "footprint": "Fridge (15mK)"},
            {"provider": "IonQ Cloud (Aria)", "t1_coherence_sec": 2.000000, "gate_error_rate": 0.0004, "readout_fidelity": 0.9950, "gate_speed_us": 150.0, "qubit_capacity": 25, "connectivity": "All-to-All", "footprint": "Laser Trap"}
        ]
    else:
        col_name = collection_mapping.get(report_type.lower())
        if not col_name:
            return Response(content=json.dumps({"detail": "Invalid report type"}), status_code=400)
            
        cursor = db[col_name].find().limit(200)
        report_data = []
        async for doc in cursor:
            doc["_id"] = str(doc["_id"])
            for k, v in doc.items():
                if isinstance(v, datetime):
                    doc[k] = v.isoformat()
            report_data.append(doc)

    if report_format.lower() == "json":
        json_content = json.dumps({
            "report_type": report_type,
            "generated_by": current_user.username,
            "timestamp": datetime.now().isoformat(),
            "metrics": report_data
        }, indent=2)
        return Response(content=json_content, media_type="application/json", headers={"Content-Disposition": f"attachment; filename={report_type}_report.json"})

    elif report_format.lower() == "csv":
        output = io.StringIO()
        if report_data:
            fieldnames = list(report_data[0].keys())
            writer = csv.DictWriter(output, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(report_data)
        else:
            output.write("No data found")
        return Response(content=output.getvalue(), media_type="text/csv", headers={"Content-Disposition": f"attachment; filename={report_type}_report.csv"})

    elif report_format.lower() == "pdf":
        # Simulating simple PDF byte stream
        pdf_bytes = io.BytesIO()
        pdf_bytes.write(b"%PDF-1.4\n")
        pdf_bytes.write(f"%% TwinQ-Map Report: {report_type} generated by {current_user.username}\n".encode())
        pdf_bytes.write(b"1 0 obj <</Type /Catalog /Pages 2 0 R>> endobj\n")
        pdf_bytes.write(b"%%EOF\n")
        pdf_bytes.seek(0)
        return StreamingResponse(pdf_bytes, media_type="application/pdf", headers={"Content-Disposition": f"attachment; filename={report_type}_report.pdf"})

    return {"detail": "Format not supported"}
